import type { Module, Cartridge, Patch, ProductPages } from './types';

export const MODULES: Module[] = [
  {
    idx: '01', slug: 'i-show-you-light',
    name: 'I Show You Light', fn: 'Oscillator',
    hp: 16, phase: 'PHASE 3', redacted: true,
    core: 'Optical tone-wheel. BLDC motor spins a cut disc; LED→photodiode reads the pattern. Swappable discs = different waveforms. Piezo stylus picks up surface texture (DUST out).',
  },
  {
    idx: '02', slug: 'body-blood-and-salt',
    name: 'Body Blood And Salt', fn: 'Liquid synth / processor',
    hp: 20, phase: 'PHASE 5', redacted: true,
    core: 'Body fluids and skin in the audio path. Four touch pads — gate, filter, bend, chaos — plus a liquid well with swappable electrodes.',
  },
  {
    idx: '03', slug: 'all-bones-dust',
    name: 'All Bones Dust', fn: 'Waveshaper / distortion / VCA',
    hp: 10, phase: 'SHIP — PHASE 1', redacted: true,
    core: 'Audio transformer in saturation + mechanical rattle plate.',
  },
  {
    idx: '04', slug: 'be-careful',
    name: 'Be Careful', fn: 'Glass resonant filter',
    hp: 'TBD', phase: 'PHASE 3', redacted: true,
    core: 'Glass plate as filter element. Motorised clamp shifts effective length = cutoff. Self-oscillates near Q=max. Plate can crack.',
  },
  {
    idx: '05', slug: 'fuck-abandoned-sleep',
    name: 'Fuck Abandoned Sleep', fn: 'Pendulum LFO',
    hp: 8, phase: 'PHASE 3', redacted: true,
    core: 'Brass weight on a carbon rod. Optical readout, electromagnet sustains the swing.',
  },
  {
    idx: '06', slug: 'is-my',
    name: 'Is My', fn: 'MOSFET shaper · VCA · ring · gate',
    hp: 10, phase: 'PHASE 2', redacted: false,
    core: 'MOSFET core from a trophy drone ESC. Three modes — SHAPER / RING / GATE — switched from an external pilot remote over MIDI/TRS. Edition of 13 with documented provenance.',
  },
  {
    idx: '07', slug: 'last-day',
    name: 'Last Day', fn: 'Delay / amp / EQ',
    hp: 40, phase: 'PHASE 2', redacted: true,
    core: 'Pre-apocalypse finaliser. Oil can delay + solar-powered starved amplifier + inductive EQ with a tongue resonator.',
  },
  {
    idx: '08', slug: 'and-my',
    name: 'And My', fn: 'Crossfader · TBD',
    hp: 'TBD', phase: 'PHASE 2', redacted: true,
    core: 'Stereo bridge between Last Day and Last Night.',
  },
  {
    idx: '09', slug: 'last-night',
    name: 'Last Night', fn: 'Natura reverb · post-apocalyptic phaser · function generator',
    hp: 40, phase: 'SHIP — PHASE 1', redacted: false, flagship: true,
    core: 'Swappable plates of wood, stone, metal, bone, glass. Surface exciter + dual piezo. Solenoid damper, freeze loop. No DSP.',
  },
];

export const CARTRIDGES: Cartridge[] = [
  { sw: 'sw-oak',      nm: 'Oak / raw',       rt: '0.1–0.3 s', ch: 'Warm, soft, perc. The wood baseline.' },
  { sw: 'sw-maple',    nm: 'Maple / shellac', rt: '0.2–0.5 s', ch: 'Violin-bright. Most musical.' },
  { sw: 'sw-marble',   nm: 'Marble',          rt: '0.8–2 s',   ch: 'Cathedral. Warm and slow.' },
  { sw: 'sw-brass',    nm: 'Brass',           rt: '1–3 s',     ch: 'Bell-like, sitar shimmer.' },
  { sw: 'sw-steel',    nm: 'Spring steel',    rt: '2–6 s',     ch: 'Infinite shimmer. 0.5 mm.' },
  { sw: 'sw-bone',     nm: 'Scapula bone',    rt: '1–3 s',     ch: 'Dry, ritual, percussive.' },
  { sw: 'sw-glass',    nm: 'Pyrex glass',     rt: '2–6 s',     ch: 'Crystalline. Compatible with Be Careful.' },
  { sw: 'sw-nephrite', nm: 'Nephrite',        rt: '1–4 s',     ch: 'Singing, meditative, ancient.' },
];

export const PATCHES: Patch[] = [
  { nm: 'Drone Cathedral', sub: '01 → 04 → 09',           dur: 'Q∞ / freeze' },
  { nm: 'Red Mirage',      sub: 'EXT → 07 → 09',          dur: 'Dub kill + drag' },
  { nm: 'Pendulum Clock',  sub: '05 → 01 → 03 → 07',      dur: 'Self-evolving' },
  { nm: 'Glass and Bone',  sub: '01·dust → 04 → 03 → 09', dur: 'Mineral perc.' },
  { nm: 'Day Into Night',  sub: '07 ⇌ 09 (FB loop)',      dur: 'Infinite decay' },
  { nm: 'Solar Storm',     sub: '07 standalone, SUN 0',   dur: 'Noise / live' },
];

export const PRODUCT_PAGES: ProductPages = {
  'is-my': {
    quote: 'The hand that flew now plays.',
    intro: 'A VCA-saturator-shaper with three modes (SHAPER / RING / GATE), built around a MOSFET stage harvested from a flight-controller ESC. The module is operated from an external pilot remote — a joystick, knobs, foot switch, on a tethered MIDI/TRS link.',
    stats: [
      { k: 'Format',  v: 'Eurorack · 10 HP + remote' },
      { k: 'Power',   v: '±12 V · 60 mA (remote: LiPo · USB-C)' },
      { k: 'Core',    v: 'MOSFET stage from FPV drone ESC' },
      { k: 'Modes',   v: 'SHAPER · RING · GATE (switched at remote)' },
      { k: 'Link',    v: 'TRS · MIDI Type A · 14-bit on joystick' },
      { k: 'Edition', v: '13 numbered · provenance certificate' },
      { k: 'Phase',   v: 'Phase 2 · ships Q4 2026' },
      { k: 'Price',   v: '€ 1 480 (module + remote)' },
    ],
    physical: [
      "Each module's gain stage is built around a power MOSFET pulled from a flight-controller ESC of a downed drone. The board is identified — model, region, date — and a photograph travels with the unit as a provenance certificate. The component does the same job it did in flight: it switches power. The signal is just smaller now.",
      'In SHAPER mode the MOSFET runs as a VCA with controllable saturation; Drive pushes the device into nonlinearity, Bias offsets the operating point (even ↔ odd harmonics). In RING mode an internal carrier (200 Hz–10 kHz) modulates duty cycle against the audio — metallic, inharmonic. In GATE mode the same device is a hard limiter + noise gate; transients become percussive, tails are cropped.',
      'Mode switching crossfades over ~50 ms to suppress clicks. Because each ESC is a different unit with different thermal history and silicon variance, every numbered module sounds slightly different. This is documented, not corrected.',
    ],
    sigchain: [
      'AUDIO IN ──► input buffer ──► MOSFET shaper core ──► output buffer ──► AUDIO OUT',
      '                                ▲',
      'VIDEO IN ──► audifier ──────────┤  (composite NTSC/PAL as parallel source)',
      '                                ▲',
      'CV bus ────────────────────────┘  (DRIVE / BIAS / LEVEL / TONE)',
      '                                ▲',
      '                       MIDI IN ◄── pilot remote (TRS, MIDI Type A)',
      '',
      'Remote outs: X / Y / GATE on 3.5 mm jacks — patch to any other module.',
    ],
    controls: [
      { ctrl: 'LEVEL',    fn: 'VCA gain. Knob on remote, CV on panel',                cv: true  },
      { ctrl: 'DRIVE',    fn: 'Saturation / PWM carrier / upper threshold',           cv: true  },
      { ctrl: 'BIAS',     fn: 'Operating-point offset (mode-dependent)',              cv: true  },
      { ctrl: 'TONE',     fn: 'Spectral tilt after the core',                         cv: true  },
      { ctrl: 'MODE',     fn: 'SHAPER · RING · GATE (3-position toggle, remote)',     cv: false },
      { ctrl: 'ARM',      fn: 'Global gate enable. Foot switch can also drive it.',   cv: false },
      { ctrl: 'LINK',     fn: 'Joystick axis link · independent / synchronous',       cv: false },
      { ctrl: 'JOYSTICK', fn: 'X→BIAS · Y→DRIVE · press→GATE trigger (14-bit MIDI)',  cv: false },
    ],
    remote: {
      blurb: 'The pilot remote is the module\'s interface. It runs on its own LiPo and charges over USB-C — which also doubles as a USB-MIDI controller for DAW use. The body is either a generic CNC enclosure or, when a donor is available, the original radio handset, fully retained as found.',
      layout: [
        'Top row     ARM · MODE · LINK              (left hand, toggles)',
        'Left zone   LEVEL · TONE · LED activity   (left hand, knobs)',
        'Right zone  Joystick · press = GATE       (right hand)',
        'Lower edge  Foot · MIDI OUT · CV OUT × 3  (X / Y / GATE)',
      ],
    },
    uses: [
      'Live performance: foot switch holds ARM, the joystick shapes the signal in real time, the CV outs simultaneously modulate the rest of the system. One gesture, four modules moving.',
      'Studio: USB-MIDI to the DAW, the remote becomes a generic controller, the module is silent unless armed.',
      "Hybrid: drive the module from another module's CV (panel inputs override the remote), keep the remote as a CV source for the rest of the rack.",
    ],
  },

  'last-night': {
    quote: 'A post-apocalyptic resonator on swappable plates. A Geiger counter and an old gramophone.',
    intro: 'An analogue multi-effect workstation. A surface exciter drives a thin plate held in a swappable cartridge — wood, stone, metal, bone, glass, jade. Two piezo pickups read the resonance from the other face. A solenoid damps the plate from above. Each cartridge is a different room.',
    stats: [
      { k: 'Format',     v: 'Eurorack 40 HP / pedal big-box (203×140×40 mm)' },
      { k: 'Power',      v: '±12 V · 200 mA (450 mA peak)' },
      { k: 'I/O',        v: 'Mono in (Eurorack) / stereo in summed (pedal) · stereo out · 3.5 mm TS + sidechain' },
      { k: 'Exciter',    v: 'Dayton DAEX32Q-4 · 3 W / 8 W peak (module-side)' },
      { k: 'Pickups',    v: '2 × piezo 27 mm · in-module contact · PVDF (premium)' },
      { k: 'Damper',     v: 'Felted solenoid · DAMP / TOLL / STALL · ~2 mm gap' },
      { k: 'Front end',  v: 'LSK489A dual-JFET preamp · ×23 gain' },
      { k: 'Cartridges', v: '6 ship · 6 more in Phase 2' },
      { k: 'Phase',      v: 'SHIP — PHASE 1 · 3-4 months made-to-order' },
      { k: 'Price',      v: '€ 640 · cartridge € 25–95' },
    ],
    physical: [
      'The instrument is the plate. A 100 mm long, 20–60 mm tall, 0.5–6 mm thick sheet of material — wood, stone, metal, glass, bone — sits in a cartridge that is nothing but the plate, its finish, a frame and four N42 magnets. The transducer engine lives in the module, not the cartridge: a module-side surface exciter spring-contacts the front of the plate and drives it into its flexural modes; two 27 mm piezo pickups spring-contact the back at different positions (near = bright, far = warm); a felted solenoid sits ~2 mm off the surface.',
      'Because the cartridge carries no electronics and no connectors, a swap is purely mechanical — four neodymium magnets and a spring-loaded retention pin align and hold it (~5 N), in about ten seconds, rated past a thousand insertions. The Hi-Z piezo signal never crosses a swappable contact, so the noise floor stays low and the cartridge stays cheap and unbreakable. Six materials ship in Phase 1: raw oak, linseed oak, shellac maple, marble, brass, spring steel. Phase 2 adds ebony, nephrite, copper, pyrex glass, scapula bone, titanium.',
      'The solenoid is triple-function on CV: DAMP holds the felt against the plate to shorten the tail, TOLL fires a 5–10 ms strike so the plate rings like a bell with no input, STALL latches a sustained hold. Everything downstream is analogue — a class-AB driver feeds the exciter, an LSK489A dual-JFET front-ends the piezos, an LM13700 OTA runs the envelope-follower VCA, and an always-on 4-stage OTA phaser is shaped by an analogue Function Generator (Tides-class LFO with rise/fall/depth and four outputs). A zener source mixes in as continuous hiss or, via the COLOR knob, as Geiger-counter clusters. Feedback is SPICE-verified stable with LED soft-clipping. No DSP touches the signal at any point.',
    ],
    sigchain: [
      'IN ──► Hi-Z buffer ──► Pre-emphasis EQ ──► DRIVE ──► Class-AB driver ──► EXCITER',
      '                                                                            │',
      '                                                                       [PLATE]',
      '                                                                            │',
      '                                                  Piezo A ──┐     Piezo B ──┘',
      '                                                            └──► LSK489A dual JFET preamp',
      '                                                                            │',
      '                                                            POSITION xfade ──┤',
      '                                                                            ▼',
      '                                              De-emphasis ──► Tone LPF ──► LED clipper',
      '                                                                            │',
      '                                                          Envelope follower VCA (LM13700)',
      '                                                                            │',
      '                                                  ┌───── FEEDBACK loop ◄────┤',
      '                                                  │                         │',
      '                                                  └► FREEZE switch          ▼',
      '                                                                       Mix + Noise',
      '                                                                            │',
      '                                                              OUT L ──── OUT R',
      '',
      'Solenoid:  CV DAMP ──► 2N7000 ──► coil ──► felt tip ──► [PLATE]',
      'Sidechain: SIDE IN  ──► summed into driver (external excitation)',
    ],
    controls: [
      { ctrl: 'DRIVE',     fn: 'Exciter signal level — quiet shimmer → self-oscillation',       cv: true  },
      { ctrl: 'FEEDBACK',  fn: 'Wet-to-driver recirculation. SPICE-stable, LED-clipped',        cv: true  },
      { ctrl: 'FREEZE',    fn: 'Toggle: input muted, loop locks at 100 %. Infinite sustain',    cv: true  },
      { ctrl: 'MIX',       fn: 'Dry / wet balance',                                             cv: true  },
      { ctrl: 'PHASE',     fn: 'Always-on 4-stage OTA phaser — feedback intensity morph',       cv: true  },
      { ctrl: 'POSITION',  fn: 'Crossfade between piezo A (bright) and piezo B (warm)',         cv: true  },
      { ctrl: 'TONE',      fn: 'Post-LPF, 158 Hz – 15.9 kHz',                                   cv: true  },
      { ctrl: 'ATTACK',    fn: 'Envelope-follower attack, 1–48 ms',                             cv: false },
      { ctrl: 'DECAY',     fn: 'Envelope-follower decay, 10 ms – 1 s',                          cv: true  },
      { ctrl: 'BOOST',     fn: 'Pre-emphasis amount (0 → +8 dB) compensating HF absorption',    cv: false },
      { ctrl: 'NOISE',     fn: 'Zener-noise mix into the wet path',                             cv: false },
      { ctrl: 'COLOR',     fn: 'Noise LPF, white → brown',                                      cv: false },
      { ctrl: 'CV DAMP',   fn: 'Solenoid drive — felt tip presses the plate',                   cv: true  },
      { ctrl: 'SIDE IN',   fn: 'External signal excites the plate independent of the main in',  cv: false },
    ],
    cartridges: [
      'Oak (raw) — 100×40×4 mm · 12 g · RT60 0.1–0.3 s · warm, soft, percussive. The wood baseline.',
      'Maple (shellac) — 100×35×4 mm · 10 g · RT60 0.2–0.5 s · violin-bright, the most musical of the wood set.',
      'Marble — 100×50×5 mm · 68 g · RT60 0.8–2 s · cathedral, warm and slow.',
      'Brass — 100×30×3 mm · 77 g · RT60 1–3 s · bell-like, sitar shimmer.',
      'Spring steel — 100×20×0.5 mm · 8 g · RT60 2–6 s · infinite shimmer; the ribbon of the set.',
      'Scapula bone — 100×40×4 mm · ~30 g · RT60 1–3 s · dry, ritual, percussive.',
      'Phase 2 — ebony, nephrite, copper, pyrex glass (also compatible with Be Careful), titanium.',
    ],
    uses: [
      'Drone cathedral: low-speed source → Be Careful → Last Night with stone or marble cartridge, freeze engaged. The room becomes the instrument.',
      'Dub finalizer: external audio (DJ deck, dub plate) → Last Day oil delay → Last Night with wood cartridge. Kill on Last Day, freeze on Last Night, and the echo dies inside the room.',
      'Sidechain rhythms: a kick from another module hits SIDE IN; the plate breathes in time without the kick passing through the wet signal. The room answers the room.',
      'Two-module loop: Last Day FB SEND → Last Night IN → Last Night SIDE OUT → Last Day FB RETURN. Delay and reverb feed each other until something gives.',
    ],
    safety: [
      'Audio through the piezos sits at sub-millivolt levels — no isolation required.',
      'Solenoid runs at ~300 mA with a flyback diode; the felt tip cannot impact the plate hard enough to crack it under normal CV.',
      'Glass and ceramic cartridges can self-destruct at maximum feedback. Replacement plates are €25–95. The name is not a metaphor.',
    ],
  },
};
