// ═══════════════════════════════════════
// МЕМЫ ЭПОХИ НА СТЕНАХ — надписи на постройках эпох: проступают, если
// постоять у стены. Граффити своего века и тех, кто пришёл позже и
// расписался поверх. Ключ — как в arch_looks.js; строки короткие.
// ═══════════════════════════════════════
export const ARCH_WALLS = {
  "axial:east:застава на перевале": ["XI CHU YANG GUAN","WU GU REN"],
  "axial:plain:курган с каменной бабой": ["ЗДЕСЬ БЫЛ ВАСЯ"],
  "axial:south:дорический храм": ["ΛΕΑΓΡΟΣ ΚΑΛΟΣ","BYRON"],
  "axial:south:зиккурат Этеменанки": ["MENE MENE","TEKEL UPHARSIN"],
  "axial:south:пилон с обелиском": ["ΕΓΡΑΦΕ ΔΕ ΜΕ ΑΡΧΩΝ","AN 6 DE LA RÉPUBLIQUE"],
  "catastrophes:east:купол-остов": ["HAHA WA BUJI","NINOSHIMA E"],
  "catastrophes:east:мост львов": ["1937·VII·7","DAO CI YI YOU"],
  "catastrophes:north:вмёрзший барк": ["FRAM","85°57'N 1895"],
  "catastrophes:north:мачта дирижабля": ["NORGE 12·V·1926","ITALIA 1928"],
  "catastrophes:plain:Дворец Советов": ["ЗДЕСЬ БУДЕТ ДВОРЕЦ","Вход в бассейн →"],
  "catastrophes:plain:градирня и цех": ["ПЯТИЛЕТКУ — В 4 ГОДА","СЛАВА ТРУДУ"],
  "catastrophes:south:вышка с факелом": ["KILROY WAS HERE"],
  "catastrophes:west:гранд-отель «Бездна»": ["SOUS LES PAVÉS,","LA PLAGE","NE TRAVAILLEZ JAMAIS"],
  "catastrophes:west:собор с обломком шпиля": ["FATHER FORGIVE","WOT, NO ROOF?"],
  "enlightenment:east:экзаменационные кельи": ["TIAN ZI DI YI HAO","TIAN DI XUAN HUANG"],
  "enlightenment:north:оранжерея Линнея": ["INNOCUE VIVITO","NUMEN ADEST","Citrus medica · Asia"],
  "enlightenment:plain:потёмкинский фасад": ["ЧУДИЩЕ ОБЛО, ОЗОРНО,","ОГРОМНО, СТОЗЕВНО","И ЛАЯЙ"],
  "enlightenment:plain:шпиль с ангелом": ["ПЕТЕРБУРГУ","БЫТЬ ПУСТУ","УРОВЕНЬ ВОДЫ 1824"],
  "enlightenment:south:пирамида в лесах": ["SCOPERTA DA G. BELZONI","2. MAR. 1818"],
  "enlightenment:south:сфинкс в лесах": ["AN VII","UNE PAGE D'HISTOIRE","NE DOIT PAS ÊTRE SALIE"],
  "enlightenment:south:форт со стелой": ["CAPTURED IN EGYPT","BY THE BRITISH ARMY","IN 1801"],
  "enlightenment:west:печатня": ["SAPERE AUDE","IL EST INTERDIT","D'INTERDIRE"],
  "enlightenment:west:ратуша с часами": ["ERIPUIT CAELO FULMEN","SCEPTRUMQUE TYRANNIS"],
  "lightgarden:east:сад камней": ["SOUS LES PAVÉS,","LA PLAGE"],
  "lightgarden:north:драккар на берегу": ["GYDA SEGIR","AT THU GAKK HEIM"],
  "lightgarden:north:ставкирка": ["THORIR REIST RUNAR","ER HANN FOR HER UM"],
  "lightgarden:plain:белокаменный храм": ["ГОСПОДИ ПОМОЗИ","РАБУ СВОЕМУ"],
  "lightgarden:south:Айя-София": ["ΚΥΡΙΕ ΒΟΗΘΕΙ","HALFTAN","ARI : MAKI"],
  "neon:east:город-соты": ["GAU LUNG WONG DAI","DENTIST 2/F →"],
  "neon:plain:Останкинская башня": ["НЕ ВЛЕЗАЙ — УБЬЁТ"],
  "neon:plain:кочегарка «Камчатка»": ["ЦОЙ ЖИВ","КИНО","Виктор, мы с тобой"],
  "neon:plain:панельная девятиэтажка": ["ЗДЕСЬ БЫЛ ВАСЯ","СПАРТАК — ЧЕМПИОН","Лена + Серёжа"],
  "neon:west:колесо обозрения": ["ОТКРЫТИЕ 1 МАЯ","СТАЛКЕР БЫЛ ТУТ"],
  "now:plain:долгострой с краном": ["СДАЧА — IV КВ.","КАКОГО ГОДА?"],
  "porticoes:east:стена в лесах": ["ZHANG SAN DAOCI YI YOU","BU DAO CHANGCHENG","FEI HAO HAN"],
  "porticoes:north:брох": ["IORSALAFARAR BRUTU","INGIGERTH ER","ALLRA KVENNA VAENST"],
  "porticoes:south:Пантеон": ["QUOD NON FECERUNT","BARBARI,","FECERUNT BARBERINI"],
  "porticoes:south:Фаросский маяк": ["ΣΩΣΤΡΑΤΟΣ ΚΝΙΔΙΟΣ","ΘΕΟΙΣ ΣΩΤΗΡΣΙ"],
  "porticoes:south:сад Эпикура": ["HOSPES,","HIC BENE MANEBIS","SUMMUM BONUM VOLUPTAS"],
  "porticoes:west:акведук": ["ADMIROR TE, PARIES,","NON CECIDISSE","RUINIS"],
  "porticoes:west:башня лимеса": ["CERVESAM NON HABENT","KILROY WAS HERE"],
  "steamshadows:east:вокзал двух часов": ["BUNMEI KAIKA","WAKON YŌSAI"],
  "steamshadows:plain:дом с мезонином": ["МИСЮСЬ, ГДЕ ТЫ?"],
  "steamshadows:plain:станция с водокачкой": ["ЗДЕСЬ БЫЛ ВАСЯ","КИПЯТОК"],
  "steamshadows:south:пароход в песках": ["KILROY WAS HERE"],
  "steamshadows:west:Эйфелева башня": ["LAVOISIER · AMPÈRE","CAUCHY · LAPLACE","INUTILE ET MONSTRUEUSE"],
  "twohearths:east:хижина Басё": ["kusa no to mo","sumikawaru yo zo","hina no ie"],
  "twohearths:north:островная обсерватория": ["NON HABERI SED ESSE"],
  "twohearths:plain:острог с ямой": ["ДО САМЫЯ СМЕРТИ,","МАРКОВНА!","ИНО ЕЩЁ ПОБРЕДЁМ"],
  "twohearths:plain:шатровая церковь": ["ГОСПОДИ ПОМОЗИ РАБУ","СВОЕМУ ИВАНУ","СКЛАД № 2"],
  "twohearths:west:мастерская линз": ["DEUS SIVE NATURA"],
};
